### ISSUE TITLE
Read final reports from previous student work

### ISSUE THREAD

**Issue by andrewgait** [UoMResearchIT/PhotonPropagation-Issue-Only#4]
Final reports from previous student work are available and should be read at the start of this project.

**Comment by andrewgait** [comment]
A wiki page has been created at https://github.com/UoMResearchIT/PhotonPropagation-Issue-Only/wiki/Previous-Project to add suitable received reports.

**Comment by andrewgait** [comment]
Some repositories for previous code can be found at

- https://github.com/gersabec/MitsubaMphys
- https://github.com/gersabec/Mitsuba-liquid

**Comment by andrewgait** [comment]
I have read reports and looked at code repositories received so far.  I am going to keep this issue open for now in case there are any further reports or code that also need to be looked at.

**Comment by ianhinder** [comment]
We should get info about what this year's CS students have done, assuming this is not what we already have.  Code and any docs or maybe the theses.

**Comment by ianhinder** [comment]
The notes from the introductory meeting mentioned:

- This year's CS bachelor students have submitted theses, mostly finished. Their work is of the most interest to us. Marco will make sure we get hold of what CS students have developed.
- 2 Mphys students finishing next week. Mostly on Geant4 comparison scenario - not the development work we are looking at. The project didn't go as far as wanted due to various reasons.
- CS student from last year: project on simulation of individual photons in Mitsuba. Open question on whether that development work is usable, as there may have been assumptions made which we can't work with. There may be issues with integrating it. Need to dig into it and look at compatibilities. No detailed code review yet. We should look at what was done and see if it can be made to work, or if a new solution is needed.

Can we get names for these people, so we can match them up against the reports we have already, just to check?

**Comment by gersabec** [comment]
You can find material from Olivia Borgstrom at https://www.dropbox.com/scl/fo/r2m1rkzh88qkifa3q3qvd/AOfxGCmcMKDYprDpu6e0_1E?rlkey=6bopxau20qv7lrt2n53kqamzf&dl=0
This includes her report, a screencast, and code for geometry conversion.

**Comment by gersabec** [comment]
I don't have the MPhys reports yet and will update once I do

**Comment by gersabec** [comment]
I can finally provide the remaining two reports. Unfortunately, they aren't of particularly high quality, so may not add much insight. I did not get anything from the other Computer Science student.
https://www.dropbox.com/scl/fi/5hd3wx5oju9wjtzfuunw7/10691641_Mitsuba_2_MPHYS.pdf?rlkey=gdiacmz65yu2tng6w8y0vw0ha&dl=0
https://www.dropbox.com/scl/fi/pr3cyvw9jg82n5nqthwwg/Mitsuba_Project_Report_II.pdf?rlkey=tcwqi2du4zj4tndth1x26btes&dl=0

**Comment by ianhinder** [comment]
Let's collect these all together; could put them in sharepoint or in this repo.
